Repository shabados/viewer, pull requests merged in 2020-10, with the labels that each got.

#314 build(frontend): update to react v17
  backend/.eslintrc
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/Error.js
  frontend/src/components/Home.js
  frontend/src/components/IconButton.js
  frontend/src/components/LineRedirect.js
  frontend/src/components/LineView.js
  frontend/src/components/LinkButton.js
  frontend/src/components/Loader.js
  frontend/src/components/Menu.js
  frontend/src/components/MenuItem.js
  frontend/src/components/Slider/Handle.js
  frontend/src/components/Slider/Tooltip.js
  frontend/src/components/Slider/TooltipRail.js
  frontend/src/components/Slider/index.js
  frontend/src/components/SourceView.js
  frontend/src/components/TranslationBlock.js
  frontend/src/index.js
Labels: Effort: 0 pt, Impact: Avg, Status: Merge

#317 test: add e2e tests using cypress
  .gitignore
  backend/.eslintrc
  cypress.json
  cypress/integration/gh-issue-open.spec.js
  cypress/integration/main.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  frontend/src/components/LineView.js
  package-lock.json
  package.json
Labels: Effort: 1 pt, Impact: Avg, Status: Merge

#318 docs: match readme/contributing of other repos
  CONTRIBUTING.md
  README.md
Labels: Effort: 1 pt, Impact: Avg, Status: Merge, Type: Docs

#309 ci: move to GitHub Actions
  .circleci/config.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
Labels: Effort: 1 pt, Impact: High, Status: Merge
